service: herbs-api-lambda

plugins:
  - serverless-offline
  - serverless-offline-sqs
  - serverless-dotenv-plugin

useDotenv: true
configValidationMode: error

provider:
  name: aws
  runtime: nodejs16.x
  region: sa-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - sqs:SendMessage
          Resource: arn:aws:sqs:${self:provider.region}:*:${env:SQS_QUEUE_NAME}
  environment:
    NODE_ENV: ${env:NODE_ENV}
    SQS_URL: ${env:SQS_ACCOUNT_URL_ID}/${env:SQS_QUEUE_NAME}
    SQS_QUEUE_NAME: ${env:SQS_QUEUE_NAME}

functions:
  apiGateway:
    name: herbs-api
    handler: index.apiHandler
    events:
      - http:
          path: adicionarFila
          method: post
  sqsFila:
    name: herbs-consumer
    handler: index.consumerHandler
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - fila
              - Arn
          batchSize: 1

resources:
  Resources:
    fila:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: fila-api-lambda

custom:
  serverless-offline-sqs:
    autoCreate: true
    apiVersion: '2012-11-05'
    endpoint: http://0.0.0.0:9324
    region: sa-east-1
    accessKeyId: root
    secretAccessKey: root
    skipCacheInvalidation: false