service: herbs-api-lambda

frameworkVersion: '3'

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs16.x
  stage: prd
  region: sa-east-1
  environment:
    SQS_URL: ${env:SQS_URL}
    SQS_QUEUE_NAME: ${env:SQS_QUEUE_NAME}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sqs:SendMessage
      Resource: arn:aws:sqs:${self:provider.region}:*:${env:SQS_QUEUE_NAME}

useDotenv: true

functions:
  apiGateway:
    name: herbs-api
    handler: src/infra/serverless/apiHandler.adicionarFila
    events:
      - httpApi:
          path: /adicionarFila
          method: post