service: herbs-api-lambda

frameworkVersion: '3'

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs16.x
  stage: prd
  region: sa-east-1
  environment:
    SQS_URL: https://sqs.${self:provider.region}.amazonaws.com/${env:SQS_ACCOUNT_ID}/${env:SQS_QUEUE_NAME}
    SQS_QUEUE_NAME: ${env:SQS_QUEUE_NAME}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sqs:SendMessage
      Resource: arn:aws:sqs:${self:provider.region}:*:${env:SQS_QUEUE_NAME}

useDotenv: true

functions:
  apiGateway:
    name: herbs-api
    handler: src/infra/serverless/apiHandler.adicionarFila
    events:
      - httpApi:
          path: /adicionarFila
          method: post
  sqsFila:
    name: herbs-consumer
    handler: src/infra/serverless/consumerHandler.observarFila
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - fila
              - Arn
          batchSize: 1

resources:
  Resources:
    fila:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${env:SQS_QUEUE_NAME}